generalOpts:
  workDir: "/app"

botOpts:
  token: "5657441460:AAHu_VJ3jBt9Nv2uXvMkuabkXkkvaD70oA8"

sheetOpts:
  spreadsheetId: "1T28n-GhmvDXeTICR3X7gzvPtU-bozmv_Ys_Uid5WK80"

oauthOpts:
  refreshToken: "1//0cyv-sqNwFjPaCgYIARAAGAwSNwF-L9IrY9AHUCU4jUpVKpH-JV3XYw5HfILjBpXp60eMJ8HZJhNi1nYL-ukoJDb3-W-loaNKiOY"